version: '3'

services:
  booking:
    image: overlord132/booking
    container_name: booking-container
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking
      REDIS_HOST: redis
  postgres:
    image: postgres:15.2
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./booking.sql:/docker-entrypoint-initdb.d/booking.sql
  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata: